force-app/main/default/objects/Data1__c/Data1__c.object-meta.xml
<CustomObject>
    <label>Data1</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Data1 Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Data1</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Data1__c/fields/Datealueofcreateddate__c.field-meta.xml
<CustomField>
    <fullName>Datealueofcreateddate__c</fullName>
    <formula>DATEVALUE( CreatedDate )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Datealueofcreateddate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/datesample.cls
public class datesample {
    public Integer dat {get;set;}
    public Data1__c data{get;set;}
   
    
    public void save(){
        Data1__c d= new Data1__c();
        System.debug('dat----'+dat); 
        Date startdate= date.today().addDays(-dat);
        system.debug('startdate-----'+startdate);
        System.debug('date.today()'+date.today());
        Integer listdata= [select count()  from Data1__c where  Datealueofcreateddate__c>=: date.today() and  Datealueofcreateddate__c<:startdate ];
        
        System.debug('listdata------'+listdata);
        IF(listdata==0){
            
        insert d;
            System.debug('d----'+d);
        }
    }

}